Input validation check is triggered multiple times #1821
enonic/lib-admin-ui pull request #1853
Opened 2021-03-15 09:01 UTC by ashklianko

Reworked validation for BaseInputTypeNotManagingAdd inheritors to avoid code duplication and redundant validation calls.
1. On user input validating only updated input instead of all occurrences.
2. Triggering validity change only when validity changed
3. Lots of small code updates

2021-03-15 16:21 UTC, alansemenov requested changes
Codacy issues and conflicts here

2021-03-19 10:21 UTC, ashklianko commented
Updated

2021-03-19 12:36 UTC, alansemenov requested changes
Still some Codacy issues... Seems like some of the new code has to be refactored for simplicity

![image](https://user-images.githubusercontent.com/11612490/111780754-19043c00-88b8-11eb-9ff1-e058bc55db06.png)

2021-03-24 15:28 UTC, alansemenov approved these changes

2021-03-24 15:28 UTC, merged