Allow commas in path section of url #3125
enonic/lib-admin-ui pull request #3126
Opened 2023-05-19 13:23 UTC by reisfmb

2023-05-21 12:29 UTC, alansemenov requested changes
There are two cases described in the task. This fix is only for the first one, we need to fix the other case as well.

2023-05-21 23:18 UTC, reisfmb commented
> There are two cases described in the task. This fix is only for the first one, we need to fix the other case as well.

I didn't fix the other case because it didn't raised any errors when I inserted it on insert link dialog.

2023-05-22 13:37 UTC, alansemenov commented
@reisfmb it fails for me instantly because of `[...]` in the url

<img width="807" alt="image" src="https://github.com/enonic/lib-admin-ui/assets/11612490/cfd9ae9a-de1b-4573-9ac7-1efa68d174ad">

2023-05-22 20:37 UTC, alansemenov approved these changes

2023-05-22 20:37 UTC, merged